name: Super Heroes App

jobs:

  on:
    push:

  testing:

    name: Lint Check and Testing
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Rund Android Linter
        run: ./gradlew lintStagingDebug

      - name: Run Unit Tests
        run: ./gradlew testStagingDebugUnitTest

      - name: Assamble Debug APK
        run: ./gradlew assembleStagingDebug
