name: Super Heroes App

on: [ push, pull_request ]

defaults:
  run:
    shell: bash

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Acces API Public Key
        env:
          PUBLIC_API_KEY: ${{ secrets.PUBLIC_API_KEY }}
        run: echo "$PUBLIC_API_KEY" | base64 -d > ./apikey.properties

      - name: Acces API Private Key
        env:
          PRIVATE_API_KEY: ${{ secrets.PRIVATE_API_KEY }}
        run: echo "$PRIVATE_API_KEY" | base64 -d > ./apikey.properties

      - name: Debug Public API Key
        run: cat PUBLIC_API_KEY -n ./apikey.properties

      - name: Debug Private API Key
        run: cat PRIVATE_API_KEY -n ./apikey.properties

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Rund Android Linter
        run: ./gradlew lintDebug

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Build Debug APK
        run: ./gradlew assembleDebug

