name: Super Heroes App

on: [ push, pull_request ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PUBLIC_API_KEY: ${{ secrets.PUBLIC_API_KEY }}
      PRIVATE_API_KEY: ${{ secrets.PRIVATE_API_KEY }}

    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Copy gradle properties file
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Access API keys
        run: |
          touch ./apikey.properties
          echo PUBLIC_API_KEY=\"$PUBLIC_API_KEY\" >> ./apikey.properties
          echo PRIVATE_API_KEY=\"$PRIVATE_API_KEY\" >> ./apikey.properties

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run Kotlin Linter
        run: ./gradlew ktlintCheck

      - name: Rund Android Linter
        run: ./gradlew lintDebug

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Build Debug APK
        run: ./gradlew assembleDebug